[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10

option_as_alt = "Both"

opacity = 1
blur = true

[colors.primary]
background = "#000000"

[font]
normal.family = "RecMonoSmCasual Nerd Font"
# normal.style = "Bold"

offset.y = 4

size = 22
