[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10

option_as_alt = "Both"

opacity = 0.7
blur = true

[colors.primary]
background = "#000000"

[font]
normal.family = "Maple Mono NF"
normal.style = "Medium"

offset.y = 4

size = 24
